name: Kids for Casa Buna
description: A passionate non-profit organization based in New York City, dedicated to enhancing the lives of children in Romania.
donate_url: https://www.paypal.com/donate/?hosted_button_id=RGMKR4SU8LN2S
contact:
  email: kidsforcasabuna@gmail.com
  phone: (917) 655-0440
social:
  - name: Twitter
    url: "#"
  - name: Facebook
    url: "#"
  - name: Instagram
    url: "#"